// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DpYbs9e6PMwbUB2xejNbfRJiTDvCb4E',
    appId: '1:579421488878:web:5ab3842c44de2e652a15ff',
    messagingSenderId: '579421488878',
    projectId: 'flutter-app-8a19c',
    authDomain: 'flutter-app-8a19c.firebaseapp.com',
    storageBucket: 'flutter-app-8a19c.appspot.com',
    measurementId: 'G-MQ6G9KSKX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAplbb6TjgKAsfn-trV11Pw88nJ3Jl0z2U',
    appId: '1:579421488878:android:63a0c1beaed44f3c2a15ff',
    messagingSenderId: '579421488878',
    projectId: 'flutter-app-8a19c',
    storageBucket: 'flutter-app-8a19c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZCZ_899R_XdMtRIoDThvAR6_14Rg4cE',
    appId: '1:579421488878:ios:5e5ed4331feb82f02a15ff',
    messagingSenderId: '579421488878',
    projectId: 'flutter-app-8a19c',
    storageBucket: 'flutter-app-8a19c.appspot.com',
    iosBundleId: 'com.example.fufuu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZCZ_899R_XdMtRIoDThvAR6_14Rg4cE',
    appId: '1:579421488878:ios:30ff8c7b0e91885c2a15ff',
    messagingSenderId: '579421488878',
    projectId: 'flutter-app-8a19c',
    storageBucket: 'flutter-app-8a19c.appspot.com',
    iosBundleId: 'com.fufuu.flutterApp.RunnerTests',
  );
}
